--FILE NAME:        
--AUTHOR NAME:      ANDREW AUXIER
--CLASS:            CMIS302 
--DATE:             20230427 (GMT+9)

DELETE FROM ACTOR;
DELETE FROM DIRECTOR;
DELETE FROM AWARD;
DELETE FROM MOVIE;
DELETE FROM CUSTOMER;
DELETE FROM DVD;
DELETE FROM VHS;
DELETE FROM RENTAL;
DELETE FROM ACTOR_MOVIE;
DELETE FROM DIRECTOR_MOVIE;
DELETE FROM AWARD_MOVIE;
DELETE FROM DVD_MOVIE;
DELETE FROM VHS_MOVIE;
DELETE FROM VHS_RENTAL;
DELETE FROM DVD_RENTAL;
DELETE FROM CUSTOMER_RENTAL;