--FILE NAME:        CREATETABLES TABLES
--AUTHOR NAME:      ANDREW AUXIER
--CLASS:            CMIS302 
--DATE:             20230427 (GMT+9)


--Standard Tables
CREATE TABLE ACTOR (
  ActorID           INT PRIMARY KEY NOT NULL,
  FirstName         VARCHAR2(30) , 
  LastName          VARCHAR2(30) 
);

CREATE TABLE DIRECTOR (
  DirectorID        INT PRIMARY KEY NOT NULL,
  FirstName         VARCHAR2(30) , 
  LastName          VARCHAR2(30) 
);

CREATE TABLE AWARD (
  AwardID           INT PRIMARY KEY NOT NULL,
  AwardName         VARCHAR2(10),  
  DateReceived      DATE,
  FirstName         VARCHAR2(30) , 
  LastName          VARCHAR2(30)   
);

CREATE TABLE MOVIE (
  MovieID           INT PRIMARY KEY NOT NULL,
  DistributorID     INT ,
  MovieName         VARCHAR2(30) ,
  DistributorName   VARCHAR2(30)   
);

CREATE TABLE DISTRIBUTOR (
  DistributorID        INT PRIMARY KEY NOT NULL,
  DistributorName      VARCHAR2(30) 
);

CREATE TABLE CUSTOMER (
  CustomerID        INT PRIMARY KEY NOT NULL, 
  FirstName         VARCHAR2(30) , 
  LastName          VARCHAR2(30) ,
  StreetAddress     VARCHAR2(30) ,
  ZipCode           NUMBER(30) 
);

CREATE TABLE DVD (
  DVDID             INT PRIMARY KEY NOT NULL, 
  Title             VARCHAR2(30)  
);

CREATE TABLE VHS (
  VHSID             INT PRIMARY KEY NOT NULL,
  Title             VARCHAR2(30)  
);

CREATE TABLE RENTAL (
  RentalID          INT PRIMARY KEY NOT NULL,    
  MovieID           INT ,
  DistributorID     INT ,
  CustomerID        INT ,
  DateOut           DATE , 
  DateDue           DATE ,
  CONSTRAINT MOVIEID_FK FOREIGN KEY (MovieID) REFERENCES MOVIE(MovieID),  
  CONSTRAINT DISTRIBUTORID_FK FOREIGN KEY (DistributorID) REFERENCES DISTRIBUTOR(DistributorID),
  CONSTRAINT CUSTOMERID_FK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)  
);



----------------------

--RELATIONAL TABLES---------------------------------
CREATE TABLE ACTOR_MOVIE (
  ACTORMOVIEID      INT PRIMARY KEY NOT NULL,
  ActorID           INT, 
  MovieID           INT,
  CONSTRAINT ACTORID_ACTOR_MOVIE_FK FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
  CONSTRAINT MOVIEID_ACTOR_MOVIE_FK FOREIGN KEY (MovieID) REFERENCES Movie(MovieID)
);

-- CREATE TABLE ACTOR_MOVIE (
--   ACTORMOVIEID      INT PRIMARY KEY NOT NULL,
--   ActorID           NUMBER REFERENCES ACTOR(ActorID),
--   MovieID           NUMBER REFERENCES MOVIE(MovieID),
--   Role              VARCHAR2(30)
-- );

---------------------------------------------------

CREATE TABLE DIRECTOR_MOVIE (
  DIRECTORMOVIEID   INT PRIMARY KEY NOT NULL,
  DirectorID        INT , 
  MovieID           INT ,
  CONSTRAINT DIRECTORID_DIRECTOR_MOVIE_FK1 FOREIGN KEY (DirectorID) REFERENCES DIRECTOR(DirectorID)  ,
  CONSTRAINT MOVIEID_DIRECTOR_MOVIE_FK2    FOREIGN KEY (MovieID)   REFERENCES MOVIE(MovieID) 
);

-----------------------------------------------------

CREATE TABLE AWARD_MOVIE (
  AWARDMOVIEID      INT PRIMARY KEY NOT NULL,
  AwardID           INT , 
  MovieID           INT ,
  CONSTRAINT AWARDID_AWARD_MOVIE_FK1    FOREIGN KEY (AwardID) REFERENCES AWARD(AwardID) ,
  CONSTRAINT MOVIEID_AWARD_MOVIE_FK2    FOREIGN KEY (MovieID) REFERENCES MOVIE(MovieID) 
);

CREATE TABLE DVD_MOVIE (
  DVDMOVIEID        INT PRIMARY KEY NOT NULL,
  DVDID             INT , 
  MovieID           INT ,
  CONSTRAINT DVDID_DVD_MOVIE_FK1      FOREIGN KEY (DVDID) REFERENCES DVD(DVDID) ,
  CONSTRAINT MOVIEID_DVD_MOVIE_FK2    FOREIGN KEY (MovieID) REFERENCES MOVIE(MovieID) 
);

CREATE TABLE VHS_MOVIE (
  VHSMOVIEID        INT PRIMARY KEY NOT NULL,
  VHSID             INT , 
  MovieID           INT ,
  CONSTRAINT VHSID_VHS_MOVIE_FK1      FOREIGN KEY (VHSID) REFERENCES VHS(VHSID) ,
  CONSTRAINT MOVIEID_VHS_MOVIE_FK2    FOREIGN KEY (MovieID) REFERENCES MOVIE(MovieID) 
);

CREATE TABLE VHS_RENTAL (
  VHSRENTALID       INT PRIMARY KEY NOT NULL,
  VHSID             INT , 
  RentalID          INT ,
  CONSTRAINT VHSID_VHS_RENTAL_FK1      FOREIGN KEY (VHSID) REFERENCES VHS(VHSID) ,
  CONSTRAINT RENTALID_VHS_RENTAL_FK2   FOREIGN KEY (RentalID) REFERENCES RENTAL(RentalID) 
);

CREATE TABLE DVD_RENTAL (
  DVDRENTALID       INT PRIMARY KEY NOT NULL,
  DVDID             INT , 
  RentalID          INT ,
  CONSTRAINT DVDID_DVD_RENTAL_FK1      FOREIGN KEY (DVDID) REFERENCES DVD(DVDID) ,
  CONSTRAINT RENTALID_DVD_RENTAL_FK2   FOREIGN KEY (RentalID) REFERENCES RENTAL(RentalID) 
);

CREATE TABLE CUSTOMER_RENTAL (
  CUSTOMER_RENTALID INT PRIMARY KEY NOT NULL,
  CustomerID        INT , 
  RentalID          INT ,
  CONSTRAINT CUSTOMERID_CUSTOMER_RENTAL_FK1 FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ,
  CONSTRAINT RENTALID_CUSTOMER_RENTAL_FK2   FOREIGN KEY (RentalID) REFERENCES RENTAL(RentalID) 
);