--FILE NAME: DROP TABLES
--AUTHOR NAME:ANDREW AUXIER
--CLASS:CMIS302 
--DATE: 20230422

--MAIN TABLES
--ACTOR

INSERT INTO ACTOR 
	--(ActorID, FirstName, LastName)
	VALUES (1, 'ACTORFIRST1', 'ACTORLAST1') ;
INSERT INTO ACTOR 
	VALUES (2, 'ACTORFIRST2', 'ACTORLAST2') ;
INSERT INTO ACTOR 
	VALUES (3, 'ACTORFIRST3', 'ACTORLAST3') ;
INSERT INTO ACTOR 
	VALUES (4, 'ACTORFIRST4', 'ACTORLAST4') ;
INSERT INTO ACTOR
	
	VALUES (5, 'ACTORFIRST5', 'ACTORLAST5') ;

--DIRECTOR
INSERT INTO DIRECTOR
	(DirectorID, FirstName, LastName)
	VALUES (1, 'DIRECTORFIRST1', 'DIRECTORLAST1') ;
INSERT INTO DIRECTOR
	VALUES (2, 'DIRECTORFIRST2', 'DIRECTORLAST2') ;
INSERT INTO DIRECTOR
	VALUES (3, 'DIRECTORFIRST3', 'DIRECTORLAST3') ;
INSERT INTO DIRECTOR
	VALUES (4, 'DIRECTORFIRST4', 'DIRECTORLAST4') ;
INSERT INTO DIRECTOR
	VALUES (5, 'DIRECTORFIRST5', 'DIRECTORLAST5') ;
--AWARD
INSERT INTO AWARD
	(AwardID, DateReceived, LastName)
	VALUES (1, 'DIRECTORFIRST1', 'DIRECTORLAST1') ;


--MOVIE


--CUSTOMER


--DVD


--VHS


--RENTAL


--RELATIONAL TABLES
--ACTOR_MOVIE


--DIRECTOR_MOVIE


--AWARD_MOVIE


--DVD_MOVIE


--VHS_MOVIE


--VHS_RENTAL


--DVD_RENTAL


--CUSTOMER_RENTAL