-- Create the tables

CREATE TABLE Engineers (
    EID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    Lastname VARCHAR2(30),
    Firstname VARCHAR2(30),
    Email VARCHAR2(30),
    Graddate DATE
);

CREATE TABLE FACULTY (
    FID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    Lastname VARCHAR2(30),
    Firstname VARCHAR2(30),
    Email VARCHAR2(30),
    Hiredate DATE
);

CREATE TABLE CLASSES (
    CID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    Subject VARCHAR2(10), /*'Subject' is a keyword. Not my fault if it does something funny, it was in the assignment guidelines*/
    Catalognbr NUMBER(3),
    Title VARCHAR2(30)
);

CREATE TABLE ClassEnrollments (
    EnID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CID NUMBER,
    FID NUMBER,
    EID NUMBER,
    FOREIGN KEY (EID) REFERENCES Engineers (EID)
    FOREIGN KEY (FID) REFERENCES Faculty (FID),
    FOREIGN KEY (CID) REFERENCES Classes (CID),
);


-- insert random stuff
INSERT INTO Engineers (Lastname, Firstname, Email, Graddate)
SELECT 
    'Last'||(ROWNUM) AS Lastname,
    'First'||(ROWNUM) AS Firstname,
    'example'||(ROWNUM)||'@example.com' AS Email,
    DATE '2023-01-01' + (ROWNUM-1) AS Graddate
FROM
    dual
CONNECT BY
    LEVEL <= 15;

--Faculty table inserts
INSERT INTO Faculty (Lastname, Firstname, Email, Hiredate)
SELECT 
    'Last'||(ROWNUM) AS Lastname,
    'First'||(ROWNUM) AS Firstname,
    'example'||(ROWNUM)||'@example.com' AS Email,
    DATE '2023-01-01' + (ROWNUM-1) AS Hiredate
FROM
    dual
CONNECT BY
    LEVEL <= 3;


--Class table inserts
INSERT INTO Classes (Subject, Catalognbr, Title)
VALUES ('AAAA', 101, 'ClassTitle1');

INSERT INTO Classes (Subject, Catalognbr, Title)
VALUES ('BBBB', 201, 'ClassTitle2');

INSERT INTO Classes (Subject, Catalognbr, Title)
VALUES ('CCCC', 301, 'ClassTitle3');


-- Enrollment table inserts
INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (1, 1, 1);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (1, 2, 2);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (1, 3, 3);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (2, 1, 4);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (2, 2, 5);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (2, 3, 6);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (3, 1, 7);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (3, 2, 8);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (3, 3, 9);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (1, 1, 10);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (2, 2, 11);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (3, 3, 12);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (1, 1, 13);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (2, 2, 14);

INSERT INTO ClassEnrollments (CID, FID, EID)
VALUES (3, 3, 15);

-- Selects all records from tables
SELECT * FROM Engineers ORDER BY EID DESC;
SELECT * FROM Faculty ORDER BY FID DESC;
SELECT * FROM Classes ORDER BY CID DESC;
SELECT * FROM ClassEnrollments ORDER BY EnID DESC;

--upate class functionality
UPDATE Faculty
SET Lastname = 'Friendship'
WHERE FID = 1;

UPDATE Engineers
SET Firstname = 'Amadeus'
WHERE EID = 1;

UPDATE Classes
SET Subject = 'IOT Cyber'
WHERE CID = 1;

--Create view to see a full picture
CREATE VIEW EnrollmentDetails AS
SELECT
    E.Lastname AS Engineer_Lastname,
    E.Firstname AS Engineer_Firstname,
    F.Lastname AS Faculty_Lastname,
    F.Email AS Faculty_Email,
    C.Subject AS Class_Subject,
    C.Title AS Class_Title
FROM
    ClassEnrollments CE
    JOIN Engineers E ON CE.EID = E.EID
    JOIN Faculty F ON CE.FID = F.FID
    JOIN Classes C ON CE.CID = C.CID;

SELECT * FROM EnrollmentDetails;

-- flip the tables. we done here.
DROP VIEW EnrollmentDetails;
DROP TABLE ClassEnrollments;
DROP TABLE Engineers;
DROP TABLE Faculty;
DROP TABLE Classes;

