"""
Project Name:   Lab 3
Module Name:    anchan_state_database.py
Author:         Andrew Auxier
Company:        UMGC, SDEV 300 6383 Building Secure Python Applications (2235) 
Description: 

    This module:
    
    provides a custom diction of values based on state, state 2-digit code, state capital, state
    population, state flower, and an image of the state flower.
    
    
"""
us_states_dictionary = {
    "alabama": {
        "state_code": "al",
        "capital": "Montgomery",
        "population": 196010,
        "flower": "Camellia",
        "image_path": "images/al.jpg",
    },
    "alaska": {
        "state_code": "ak",
        "capital": "Juneau",
        "population": 31534,
        "flower": "Forget-me-not",
        "image_path": "images/ak.jpg",
    },
    "arizona": {
        "state_code": "az",
        "capital": "Phoenix",
        "population": 1651344,
        "flower": "Saguaro Cactus Blossom",
        "image_path": "images/az.jpg",
    },
    "arkansas": {
        "state_code": "ar",
        "capital": "Little Rock",
        "population": 201029,
        "flower": "Apple Blossom",
        "image_path": "images/ar.jpg",
    },
    "california": {
        "state_code": "ca",
        "capital": "Sacramento",
        "population": 528306,
        "flower": "California Poppy",
        "image_path": "images/ca.jpg",
    },
    "colorado": {
        "state_code": "co",
        "capital": "Denver",
        "population": 699288,
        "flower": "Rocky Mountain Columbine",
        "image_path": "images/co.jpg",
    },
    "connecticut": {
        "state_code": "ct",
        "capital": "Hartford",
        "population": 119817,
        "flower": "Mountain Laurel",
        "image_path": "images/ct.jpg",
    },
    "delaware": {
        "state_code": "de",
        "capital": "Dover",
        "population": 37892,
        "flower": "Peach Blossom",
        "image_path": "images/de.jpg",
    },
    "florida": {
        "state_code": "fl",
        "capital": "Tallahassee",
        "population": 198631,
        "flower": "Orange Blossom",
        "image_path": "images/fl.jpg",
    },
    "georgia": {
        "state_code": "ga",
        "capital": "Atlanta",
        "population": 490270,
        "flower": "Cherokee Rose",
        "image_path": "images/ga.jpg",
    },
    "hawaii": {
        "state_code": "hi",
        "capital": "Honolulu",
        "population": 337088,
        "flower": "Hibiscus",
        "image_path": "images/hi.jpg",
    },
    "idaho": {
        "state_code": "id",
        "capital": "Boise",
        "population": 240713,
        "flower": "Syringa",
        "image_path": "images/id.jpg",
    },
    "illinois": {
        "state_code": "il",
        "capital": "Springfield",
        "population": 111711,
        "flower": "Violet",
        "image_path": "images/il.jpg",
    },
    "indiana": {
        "state_code": "in",
        "capital": "Indianapolis",
        "population": 871449,
        "flower": "Peony",
        "image_path": "images/in.jpg",
    },
    "iowa": {
        "state_code": "ia",
        "capital": "Des Moines",
        "population": 217891,
        "flower": "Wild Prairie Rose",
        "image_path": "images/ia.jpg",
    },
    "kansas": {
        "state_code": "ks",
        "capital": "Topeka",
        "population": 125310,
        "flower": "Sunflower",
        "image_path": "images/ks.jpg",
    },
    "kentucky": {
        "state_code": "ky",
        "capital": "Frankfort",
        "population": 27498,
        "flower": "Goldenrod",
        "image_path": "images/ky.jpg",
    },
    "louisiana": {
        "state_code": "la",
        "capital": "Baton Rouge",
        "population": 221599,
        "flower": "Magnolia",
        "image_path": "images/la.jpg",
    },
    "maine": {
        "state_code": "me",
        "capital": "Augusta",
        "population": 18257,
        "flower": "White Pine Cone and Tassel",
        "image_path": "images/me.jpg",
    },
    "maryland": {
        "state_code": "md",
        "capital": "Annapolis",
        "population": 38394,
        "flower": "Black-eyed Susan",
        "image_path": "images/md.jpg",
    },
    "massachusetts": {
        "state_code": "ma",
        "capital": "Boston",
        "population": 692600,
        "flower": "Mayflower",
        "image_path": "images/ma.jpg",
    },
    "michigan": {
        "state_code": "mi",
        "capital": "Lansing",
        "population": 119128,
        "flower": "Apple Blossom",
        "image_path": "images/mi.jpg",
    },
    "minnesota": {
        "state_code": "mn",
        "capital": "Saint Paul",
        "population": 308096,
        "flower": "Pink and White Lady's Slipper",
        "image_path": "images/mn.jpg",
    },
    "mississippi": {
        "state_code": "ms",
        "capital": "Jackson",
        "population": 160628,
        "flower": "Magnolia",
        "image_path": "images/ms.jpg",
    },
    "missouri": {
        "state_code": "mo",
        "capital": "Jefferson City",
        "population": 43579,
        "flower": "Hawthorn",
        "image_path": "images/mo.jpg",
    },
    "montana": {
        "state_code": "mt",
        "capital": "Helena",
        "population": 32234,
        "flower": "Bitterroot",
        "image_path": "images/mt.jpg",
    },
    "nebraska": {
        "state_code": "ne",
        "capital": "Lincoln",
        "population": 287401,
        "flower": "Goldenrod",
        "image_path": "images/ne.jpg",
    },
    "nevada": {
        "state_code": "nv",
        "capital": "Carson City",
        "population": 55916,
        "flower": "Sagebrush",
        "image_path": "images/nv.jpg",
    },
    "new hampshire": {
        "state_code": "nh",
        "capital": "Concord",
        "population": 43093,
        "flower": "Purple Lilac",
        "image_path": "images/nh.jpg",
    },
    "new jersey": {
        "state_code": "nj",
        "capital": "Trenton",
        "population": 84913,
        "flower": "Violet",
        "image_path": "images/nj.jpg",
    },
    "new mexico": {
        "state_code": "nm",
        "capital": "Santa Fe",
        "population": 87592,
        "flower": "Yucca Flower",
        "image_path": "images/nm.jpg",
    },
    "new york": {
        "state_code": "ny",
        "capital": "Albany",
        "population": 97904,
        "flower": "Rose",
        "image_path": "images/ny.jpg",
    },
    "north carolina": {
        "state_code": "nc",
        "capital": "Raleigh",
        "population": 474069,
        "flower": "Dogwood",
        "image_path": "images/nc.jpg",
    },
    "north dakota": {
        "state_code": "nd",
        "capital": "Bismarck",
        "population": 73670,
        "flower": "Wild Prairie Rose",
        "image_path": "images/nd.jpg",
    },
    "ohio": {
        "state_code": "oh",
        "capital": "Columbus",
        "population": 898553,
        "flower": "Scarlet Carnation",
        "image_path": "images/oh.jpg",
    },
    "oklahoma": {
        "state_code": "ok",
        "capital": "Oklahoma City",
        "population": 655057,
        "flower": "Oklahoma Rose",
        "image_path": "images/ok.jpg",
    },
    "oregon": {
        "state_code": "or",
        "capital": "Salem",
        "population": 179335,
        "flower": "Oregon Grape",
        "image_path": "images/or.jpg",
    },
    "pennsylvania": {
        "state_code": "pa",
        "capital": "Harrisburg",
        "population": 49528,
        "flower": "Mountain Laurel",
        "image_path": "images/pa.jpg",
    },
    "rhode island": {
        "state_code": "ri",
        "capital": "Providence",
        "population": 179883,
        "flower": "Violet",
        "image_path": "images/ri.jpg",
    },
    "south carolina": {
        "state_code": "sc",
        "capital": "Columbia",
        "population": 133273,
        "flower": "Yellow Jessamine",
        "image_path": "images/sc.jpg",
    },
    "south dakota": {
        "state_code": "sd",
        "capital": "Pierre",
        "population": 14246,
        "flower": "Pasque Flower",
        "image_path": "images/sd.jpg",
    },
    "tennessee": {
        "state_code": "tn",
        "capital": "Nashville",
        "population": 601222,
        "flower": "Iris",
        "image_path": "images/tn.jpg",
    },
    "texas": {
        "state_code": "tx",
        "capital": "Austin",
        "population": 978908,
        "flower": "Bluebonnet",
        "image_path": "images/tx.jpg",
    },
    "utah": {
        "state_code": "ut",
        "capital": "Salt Lake City",
        "population": 198029,
        "flower": "Sego Lily",
        "image_path": "images/ut.jpg",
    },
    "vermont": {
        "state_code": "vt",
        "capital": "Montpelier",
        "population": 7855,
        "flower": "Red Clover",
        "image_path": "images/vt.jpg",
    },
    "virginia": {
        "state_code": "va",
        "capital": "Richmond",
        "population": 230436,
        "flower": "American Dogwood",
        "image_path": "images/va.jpg",
    },
    "washington": {
        "state_code": "wa",
        "capital": "Olympia",
        "population": 52959,
        "flower": "Coast Rhododendron",
        "image_path": "images/wa.jpg",
    },
    "west virginia": {
        "state_code": "wv",
        "capital": "Charleston",
        "population": 51642,
        "flower": "Rhododendron",
        "image_path": "images/wv.jpg",
    },
    "wisconsin": {
        "state_code": "wi",
        "capital": "Madison",
        "population": 259680,
        "flower": "Wood Violet",
        "image_path": "images/wi.jpg",
    },
    "wyoming": {
        "state_code": "wy",
        "capital": "Cheyenne",
        "population": 63889,
        "flower": "Indian Paintbrush",
        "image_path": "images/wy.jpg",
    },
}
