--FILE NAME: DROP TABLES
--AUTHOR NAME:ANDREW AUXIER
--CLASS:CMIS302 
--DATE: 20230422

--INSERT INTO ACTOR 
--		VALUES (1, 'FIRST1', 'LAST1') ;
INSERT INTO ACTOR 
	(ActorID, FirstName, LastName)
	VALUES (2, 'FIRST2', 'LAST2') ;
INSERT INTO ACTOR 
	(ActorID, FirstName, LastName)
	VALUES (3, 'FIRST3', 'LAST3') ;
INSERT INTO ACTOR 
	(ActorID, FirstName, LastName)
	VALUES (4, 'FIRST4', 'LAST4') ;
INSERT INTO ACTOR
	(ActorID, FirstName, LastName)
	VALUES (5, 'FIRST5', 'LAST5') ;
